---
#------------------------------------------------------------------------------
# Basic PostgreSQL settings
#------------------------------------------------------------------------------
# Enter the PostgreSQL version to be installed
pgversion: 12

# By default, only stable packages from 2ndQuadrant repository are installed.
# Uncomment the next line to use snapshot packages instead of stable releases.
#repo_2ndq_maturity_level: snapshot

# Where postgres log files are kept
pg_log_file: /var/log/postgres.log

# Users for replication
replication_user:
  postgres: repuser
  barman: streaming_barman

# pg_hba.conf
pg_hba_method: md5

#------------------------------------------------------------------------------
# postgresql.conf settings
#------------------------------------------------------------------------------
postgresql_conf: |
    ### network settings
    listen_addresses = '*'

    ### memory settings
    shared_buffers = 64MB
    checkpoint_completion_target = 0.9

    ### base log settings
    log_destination = syslog
    syslog_facility = LOCAL0
    syslog_ident = postgres

    ### log customizations for better monitoring
    logging_collector = on
    log_checkpoints = on
    log_lock_waits = on
    log_min_duration_statement = 1000
    log_line_prefix = 'u=[%u] db=[%d] app=[%a] c=[%h] s=[%c:%l] tx=[%v:%x] '
    log_statement = 'ddl'
    log_temp_files = 1024
    log_autovacuum_min_duration = '1s'

    ### pg_stat_statements
    shared_preload_libraries = pg_stat_statements
    pg_stat_statements.max = 1000
    pg_stat_statements.track = all

    ### hot-standby settings
    wal_level = logical
    hot_standby_feedback = on

    ### wal archiving
    archive_timeout = 5min
    archive_mode = always
    archive_command = '/bin/true'
