---
#------------------------------------------------------------------------------
# Repositories for PostgreSQL and others
#------------------------------------------------------------------------------
# 2ndQuadrant's General Public repository
repo_2ndq_file: /etc/yum.repos.d/2ndquadrant-dl-default-{{ repo_2ndq_maturity_level | default('release') }}-pg{{ pgversion }}.repo
repo_2ndq: https://dl.2ndquadrant.com/default/{{ repo_2ndq_maturity_level | default('release') }}/get/{{ pgversion }}/rpm

# EPEL
epel_repo: epel-release

# PostgreSQL Yum Repository
pg_rpm_repo: https://download.postgresql.org/pub/repos/yum/reporpms/EL-{{ ansible_distribution_major_version }}-{{ ansible_architecture }}/pgdg-redhat-repo-latest.noarch.rpm

#------------------------------------------------------------------------------
# PostgreSQL and dependency packages to be installed
#------------------------------------------------------------------------------
# Required for following Postgres package format on RedHat
pgversion_plain: "{{ pgversion | replace('.', '') }}"

pg_packages:
  - "postgresql{{ pgversion_plain }}"
  - "postgresql{{ pgversion_plain }}-server"
  - "postgresql{{ pgversion_plain }}-contrib"
  - "postgresql{{ pgversion_plain }}-devel"
  - barman-cli
  - rsync
  - vim
  - pwgen
  - screen
  - asciinema

barman_packages:
  - barman
  - "postgresql{{ pgversion_plain }}"
  - rsync
  - vim
  - pwgen
  - screen
  - asciinema

dependency_packages:
  - python-psycopg2
  - python-pycurl
  - glibc-common
  - libselinux-python
  - policycoreutils-python
  - rsyslog
  - logrotate

#------------------------------------------------------------------------------
# PostgreSQL service
#------------------------------------------------------------------------------
pg_service: postgresql-{{ pgversion }}

#------------------------------------------------------------------------------
# PostgreSQL directories
#------------------------------------------------------------------------------
pg_bin_directory: "/usr/pgsql-{{ pgversion }}/bin"
pg_data_directory: "/var/lib/pgsql/{{ pgversion }}/data"
pg_conf_directory: "{{ pg_data_directory }}"
