---
#------------------------------------------------------------------------------
# Log settings - rsyslog and logrotate
#------------------------------------------------------------------------------
- name: Ensure postgres.log exists
  file:
    path: "{{ pg_log_file }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: 0640
    state: touch

- name: Adjust rsyslog settings for PostgreSQL
  copy:
    src: 30-rsyslog-postgresql.conf
    dest: /etc/rsyslog.d/
    owner: root
    group: root
    mode: 0644

- name: Adjust logrotate settings for PostgreSQL
  copy:
    src: "logrotate-postgresql-{{ ansible_os_family | lower }}"
    dest: /etc/logrotate.d/logrotate-postgresql
    owner: root
    group: root
    mode: 0644

- name: Restart rsyslog service
  service:
    name: rsyslog
    state: restarted
    enabled: yes

#------------------------------------------------------------------------------
# postgresql.conf config
#------------------------------------------------------------------------------
- name: Adjust postgresql.conf
  blockinfile:
    path: "{{ pg_conf_directory }}/postgresql.conf"
    insertafter: EOF
    block: |
      {{ postgresql_conf }}

#------------------------------------------------------------------------------
# pg_hba.conf config
#------------------------------------------------------------------------------
- name: Append config to pg_hba.conf
  blockinfile:
    path: "{{ pg_conf_directory }}/pg_hba.conf"
    insertafter: EOF
    block: "{{ lookup('template', 'pg_hba.conf.j2') }}"

#------------------------------------------------------------------------------
# PostgreSQL service
#------------------------------------------------------------------------------
- name: Start and enable the PostgreSQL service
  service:
    name: "{{ pg_service }}"
    state: restarted
    enabled: yes

#------------------------------------------------------------------------------
# pg_stat_statements
#------------------------------------------------------------------------------
- name: Install pg_stat_statements in postgres database
  become: yes
  become_user: postgres
  postgresql_ext:
    name: pg_stat_statements
    db: postgres
