---
- name: Include variables accordingly to OS
  include_vars:
    file: "{{ ansible_os_family | lower }}.yml"
  tags: always

- name: Add repositories
  include_tasks: add_repository.yml

- name: Install PostgreSQL & Barman
  include_tasks: install.yml

- name: Configure PostgreSQL servers
  include_tasks: configure_postgres_{{ ansible_os_family | lower }}.yml
  when: inventory_hostname in groups['postgres']

- name: Configure system (access and SSH)
  include_tasks:
    file: configure_system_ssh.yml
    apply:
      tags:
        - ssh
  tags: ssh

- name: Configure system (users and pgbench)
  include_tasks:
    file: configure_system_shell.yml
    apply:
      tags:
        - shell
  tags: shell
